package org.thingml.pressuresensor.ui;

import java.awt.Color;
import java.awt.Dimension;
import org.thingml.rtcharts.swing.GraphBuffer;
import org.thingml.rtcharts.swing.GraphPanel;
import org.thingml.rtcharts.swing.LineGraphPanel;

/**
 *
 * @author ffl
 */
public class MainFrame extends javax.swing.JFrame {

    
    GraphBuffer graph_buffer_pA = new GraphBuffer(500);
    GraphPanel graph_panel_pA =  new LineGraphPanel(graph_buffer_pA, "Pressure A", 100100, 100300, 10, Color.GREEN);
    
    GraphBuffer graph_buffer_pB = new GraphBuffer(500);
    GraphPanel graph_panel_pB =  new LineGraphPanel(graph_buffer_pB, "Pressure B", 100100, 100300, 10, Color.GREEN);
    
    GraphBuffer graph_buffer_pDiff = new GraphBuffer(500);
    GraphPanel graph_panel_pDiff =  new LineGraphPanel(graph_buffer_pDiff, "Pressure Difference (B - A)", -30, 30, 5, Color.ORANGE);
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        graph_panel_pA.setPreferredSize(new Dimension(800, 160));
        graph_panel_pB.setPreferredSize(new Dimension(800, 160));
        graph_panel_pDiff.setPreferredSize(new Dimension(800, 160));
        jPanelGraphs.add(graph_panel_pA);
        jPanelGraphs.add(graph_panel_pB);
        jPanelGraphs.add(graph_panel_pDiff);
        pack();
        graph_panel_pA.start();
        graph_panel_pB.start();
        graph_panel_pDiff.start();
    }
    
    public void insertData(int pa, int pb, int pdiff) {
        graph_buffer_pA.insertData(pa);
        graph_buffer_pB.insertData(pb);
        graph_buffer_pDiff.insertData(pdiff);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPort = new javax.swing.JLabel();
        jTextFieldPort = new javax.swing.JTextField();
        jButtonStop = new javax.swing.JButton();
        jButtonStart = new javax.swing.JButton();
        jPanelGraphs = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelPort.setText("Serial Port: ");

        jTextFieldPort.setEditable(false);
        jTextFieldPort.setText("COM28");

        jButtonStop.setText("Stop");
        jButtonStop.setEnabled(false);

        jButtonStart.setText("Start");
        jButtonStart.setEnabled(false);

        jPanelGraphs.setLayout(new javax.swing.BoxLayout(jPanelGraphs, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelGraphs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPort, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonStop)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPort)
                    .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStop)
                    .addComponent(jButtonStart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelGraphs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JPanel jPanelGraphs;
    private javax.swing.JTextField jTextFieldPort;
    // End of variables declaration//GEN-END:variables
}
